version: '3.8'

services:
  # Next.js Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: memorial-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for rate limiting and sessions
  redis:
    image: redis:7-alpine
    container_name: memorial-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: memorial-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - certbot-web:/var/www/certbot:ro
      - certbot-certs:/etc/letsencrypt:ro
      - nginx-logs:/var/log/nginx
    networks:
      - app-network
      - crowdsec-network
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot for SSL certificates
  certbot:
    image: certbot/dns-porkbun
    container_name: memorial-certbot
    restart: "no"
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-web:/var/www/certbot
      - ./certbot:/etc/certbot:ro
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_KEY=${PORKBUN_SECRET_KEY}
    command: >
      sh -c "
        trap exit TERM;
        while :; do
          certbot renew --quiet --dns-porkbun --dns-porkbun-credentials /etc/certbot/porkbun.ini;
          sleep 12h & wait $${!};
        done
      "

  # CrowdSec Security Engine
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: memorial-crowdsec
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/nginx crowdsecurity/base-http-scenarios
      - GID=${GID:-1000}
    volumes:
      - crowdsec-db:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec
      - nginx-logs:/var/log/nginx:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
    networks:
      - crowdsec-network
    healthcheck:
      test: ["CMD", "cscli", "metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CrowdSec Bouncer for Nginx
  crowdsec-nginx-bouncer:
    image: crowdsecurity/nginx-crowdsec-bouncer
    container_name: memorial-bouncer
    restart: unless-stopped
    environment:
      - CROWDSEC_BOUNCER_API_KEY=${CROWDSEC_BOUNCER_API_KEY}
      - CROWDSEC_AGENT_HOST=crowdsec:8080
    volumes:
      - ./nginx/bouncer.conf:/etc/nginx/conf.d/crowdsec.conf:ro
    networks:
      - crowdsec-network
    depends_on:
      - crowdsec

  # Watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower
    container_name: memorial-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: --interval 3600 --cleanup

  # Tailscale sidecar for admin access
  tailscale:
    image: tailscale/tailscale:latest
    container_name: memorial-tailscale
    hostname: memorial-admin
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./tailscale:/config:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - app-network
    depends_on:
      - app

  # Log aggregation
  promtail:
    image: grafana/promtail
    container_name: memorial-promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - nginx-logs:/var/log/nginx:ro
      - ./promtail/promtail.yml:/etc/promtail/config.yml:ro
    networks:
      - app-network
    command: -config.file=/etc/promtail/config.yml

networks:
  app-network:
    driver: bridge
    internal: false
  crowdsec-network:
    driver: bridge

volumes:
  redis-data:
  crowdsec-db:
  crowdsec-config:
  certbot-certs:
  certbot-web:
  nginx-logs:
  tailscale-state: